# Generated by Django 2.1.1 on 2018-09-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20180906_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rdifTag',
            new_name='rfidfTag',
        ),
    ]
