# Generated by Django 2.1.1 on 2018-09-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20180906_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rfidfTag',
            new_name='rfidTag',
        ),
    ]
